* 06/19/20
Today was really shit.  I "moved out" of my apartment, but it was nothing liked I had hoped it would be.
I got into my apartment around 3pm and found that everything had already been packed up for me, but with 
the catch that the people doing the packing seemed to not care at all for any of my stuff.
I found my ps4 box on my fire escape, poked full of holes; my posters were folded to shit and jammed in a box,
my computer monitor was jammed in another box with shoes on top of it, and things were just needlessly torn apart
and broken, like boxes and stuff.  The apartment was an absolute mess for no reason.  It feels terrible.
I really liked my room and I almost feel violated to have some idiots go through all my stuff and "pack"
it for me.  I wanted just one last send off to two years at BU, and all I'm left with is a nice "fuck you"
and 6 boxes to sift through in 2 hours. 
It was all just really bad.  I don't think one thing went right.  We had to pack everything in Christina's mom's 
tiny sedan so it took two trips, and we were rushing to put everything in so quickly that everything ended up
being jammed in trash bags.  I don't really know where anything is and I had to leave some stuff in the apartment.
I wish I could have taken some of my candles, but it doesn't really matter.  I got my christmas lights and 
my liverpool jerseys, so I'm kind of okay.  But what they did to my posters is so bad.  It'll take weeks
to fix them, and hopefully they'll be somewhat okay. My signed Toh kay poster was folded the worst, my 
darjeeling limited one was nearly destroyed. It's just such a blatant disregard for someone else's things.
I don't know what idiot thought that they were fit to handle people's things. 
